-- 사용자 데이터 삽입
INSERT INTO MEMBER (MEMBER_NO, ENROLL_DATE, EMAIL, MEMBER_GRADE, MEMBER_ID, MEMBER_NAME, PHONE_NO, MEMBER_PW)
SELECT NEXT VALUE FOR MEMBER_SEQ, '20250411', 'admin@gmail.com', 'ADMIN', 'admin', '관리자', '010-2738-8240', '$2a$10$fOYgbQQS00vAIZap6GG2qOhuKFQhaUFJDbRzzwJOJzMUZYhJzHD32'
WHERE NOT EXISTS (SELECT 1 FROM MEMBER WHERE MEMBER_ID = 'admin');

INSERT INTO MEMBER (MEMBER_NO, ENROLL_DATE, EMAIL, MEMBER_GRADE, MEMBER_ID, MEMBER_NAME, PHONE_NO, MEMBER_PW)
SELECT NEXT VALUE FOR MEMBER_SEQ, '20250411', 'limsohyeonn@gmail.com', 'USER', 'shlim', '임소현', '010-2738-8240', '$2a$10$fOYgbQQS00vAIZap6GG2qOhuKFQhaUFJDbRzzwJOJzMUZYhJzHD32'
WHERE NOT EXISTS (SELECT 1 FROM MEMBER WHERE MEMBER_ID = 'shlim');

-- 카테고리 데이터 삽입
INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 1000, 1000, '디자인', 'Y'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 1000);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 2000, 2000, 'IT/프로그래밍', 'Y'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 2000);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 3000, 3000, '영상/사진/음향', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 3000);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 4000, 4000, '교육', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 4000);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 5000, 5000, '문서/글쓰기', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 5000);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 6000, 6000, '비즈니스컨설팅', 'Y'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 6000);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 7000, 7000, '주문제작', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 7000);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 1000, 1100, '로고 디자인', 'img/index/carousel/category-11.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 1100);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 1000, 1200, '상세페이지 디자인', 'img/index/carousel/category-12.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 1200);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 1000, 1300, '배너 디자인', 'img/index/carousel/category-13.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 1300);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 1000, 1400, '캐릭터 디자인', 'img/index/carousel/category-14.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 1400);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 1000, 1500, '브랜딩', 'img/index/carousel/category-15.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 1500);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 1000, 1600, '인쇄물 디자인', 'img/index/carousel/category-16.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 1600);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 2000, 2100, '모바일앱개발', 'img/index/carousel/category-21.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 2100);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 2000, 2200, '웹사이트개발', 'img/index/carousel/category-22.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 2200);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 2000, 2300, '프로그램 개발', 'img/index/carousel/category-23.jpg'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 2300);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 2000, 2400, '데이터베이스', 'img/index/carousel/category-24.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 2400);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 2000, 2500, '게임개발', 'img/index/carousel/category-25.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 2500);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 2000, 2600, '보안', 'img/index/carousel/category-26.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 2600);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 2000, 2700, '파일변환', 'img/index/carousel/category-27.jpg'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 2700);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 3000, 3100, '영상촬영ㆍ편집', 'img/index/carousel/category-31.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 3100);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 3000, 3200, '유튜브 제작', 'img/index/carousel/category-32.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 3200);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 3000, 3300, '애니메이션제작', 'img/index/carousel/category-33.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 3300);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 3000, 3400, '더빙ㆍ녹음', 'img/index/carousel/category-34.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 3400);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 3000, 3500, '음악ㆍ사운드', 'img/index/carousel/category-35.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 3500);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 4000, 4100, '문서작성', 'img/index/carousel/category-41.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 4100);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 4000, 4200, '이력서ㆍ자기소개서', 'img/index/carousel/category-42.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 4200);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 4000, 4300, '기획서ㆍ사업계획서', 'img/index/carousel/category-43.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 4300);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 4000, 4400, '슬라이드ㆍPPT', 'img/index/carousel/category-44.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 4400);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 4000, 4500, '보고서ㆍ논문', 'img/index/carousel/category-45.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 4500);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 5000, 5100, '영어 번역', 'img/index/carousel/category-51.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 5100);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 5000, 5200, '일본어 번역', 'img/index/carousel/category-52.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 5200);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 5000, 5300, '중국어 번역', 'img/index/carousel/category-53.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 5300);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 5000, 5400, '베트남어 번역', 'img/index/carousel/category-54.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 5400);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 5000, 5500, '그 외 번역', 'img/index/carousel/category-55.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 5500);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 6000, 6100, '자기계발', 'img/index/carousel/category-61.jpg'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 6100);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 6000, 6200, '취업ㆍ이직', 'img/index/carousel/category-62.jpg'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 6200);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 6000, 6300, '마케팅ㆍ홍보', 'img/index/carousel/category-63.jpg'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 6300);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 6000, 6400, '기타 컨설팅', 'img/index/carousel/category-64.jpg'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 6400);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 6000, 6500, '업무지원ㆍcs', 'img/index/carousel/category-65.jpg'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 6500);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 7000, 7100, '인쇄', 'img/index/carousel/category-71.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 7100);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 7000, 7200, '간판', 'img/index/carousel/category-72.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 7200);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 7000, 7300, '기념품제작', 'img/index/carousel/category-73.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 7300);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 7000, 7400, '모형제작', 'img/index/carousel/category-74.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 7400);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 7000, 7500, '시스템제작', 'img/index/carousel/category-75.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 7500);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 7000, 7600, '인테리어시공', 'img/index/carousel/category-76.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 7600);

INSERT INTO CATEGORY (MAIN_CATEGORY_CD, CATEGORY_CD, CATEGORY_NAME, IMG_URL)
SELECT 7000, 7700, '패키지제작', 'img/index/carousel/category-77.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CD = 7700);