-- 사용자 데이터 삽입
INSERT INTO MEMBER (ENROLL_DATE, M_EMAIL, M_GRADE, M_ID, M_NAME, M_PHONE, M_PW)
SELECT '20250411', 'admin@gmail.com', 'ADMIN', 'admin', '관리자', '010-2738-8240', '$2a$10$fOYgbQQS00vAIZap6GG2qOhuKFQhaUFJDbRzzwJOJzMUZYhJzHD32'
    WHERE NOT EXISTS (SELECT 1 FROM MEMBER WHERE M_ID = 'admin');

INSERT INTO MEMBER (ENROLL_DATE, M_EMAIL, M_GRADE, M_ID, M_NAME, M_PHONE, M_PW)
SELECT '20250411', 'limsohyeonn@gmail.com', 'USER', 'shlim', '임소현', '010-2738-8240', '$2a$10$fOYgbQQS00vAIZap6GG2qOhuKFQhaUFJDbRzzwJOJzMUZYhJzHD32'
    WHERE NOT EXISTS (SELECT 1 FROM MEMBER WHERE M_ID = 'shlim');

-- 카테고리 데이터 삽입
INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 1000, 1000, '디자인', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 1000);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 2000, 2000, 'IT/프로그래밍', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 2000);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 3000, 3000, '영상/사진/음향', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 3000);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 4000, 4000, '교육', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 4000);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 5000, 5000, '문서/글쓰기', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 5000);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 6000, 6000, '비즈니스컨설팅', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 6000);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 7000, 7000, '주문제작', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 7000);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 1000, 1100, '로고/브랜딩', 'img/index/carousel/category-11.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 1100);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 1000, 1200, '인쇄ㆍ홍보물ㆍ배너', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 1200);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 1000, 1300, '캘리그라피ㆍ폰트', 'img/index/carousel/category-13.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 1300);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 1000, 1400, '일러스트ㆍ캐리커쳐', 'img/index/carousel/category-14.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 1400);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 1000, 1500, '간판ㆍ시공', 'img/index/carousel/category-15.png'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 1500);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 1000, 1600, '이벤트 ㆍ상세페이지', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 1600);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 1000, 1700, '의류', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 1700);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 1000, 1800, '웹툰ㆍ캐릭터ㆍ이모티콘', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 1800);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 2000, 2100, '워드프레스', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 2100);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 2000, 2200, '웹사이트개발', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 2200);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 2000, 2300, '프로그램 개발', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 2300);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 2000, 2400, '데이터베이스', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 2400);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 2000, 2500, '게임개발', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 2500);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 2000, 2600, '보안', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 2600);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 2000, 2700, '파일변환', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 2700);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 3000, 3100, '영상촬영ㆍ편집', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 3100);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 3000, 3200, '유튜브 제작', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 3200);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 3000, 3300, '애니메이션제작', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 3300);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 3000, 3400, '더빙ㆍ녹음', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 3400);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 3000, 3500, '음악ㆍ사운드', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 3500);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 4000, 4100, '외국어(영어)', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 4100);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 4000, 4200, '외국어(기타언어)', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 4200);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 4000, 4300, '취미 라이프', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 4300);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 4000, 4400, '입시/학업', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 4400);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 4000, 4500, 'pptㆍ프레젠테이션', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 4500);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 4000, 4600, '마케팅', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 4600);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 4000, 4700, '사진', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 4700);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 5000, 5100, '보도자료', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 5100);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 5000, 5200, '광고카피라이팅', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 5200);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 5000, 5300, '마케팅 글작성', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 5300);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 5000, 5400, '책ㆍ시나리오 작성', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 5400);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 5000, 5500, '논문', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 5500);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 5000, 5600, '교정ㆍ교육 첨삭', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 5600);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 5000, 5700, '기타', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 5700);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 6000, 6100, '사업계획서 투자제안서', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 6100);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 6000, 6200, '인사ㆍ노무', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 6200);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 6000, 6300, '창업컨설팅', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 6300);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 6000, 6400, '법률법무', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 6400);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 6000, 6500, '업무지원ㆍcs', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 6500);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 7000, 7100, '인쇄', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 7100);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 7000, 7200, '간판', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 7200);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 7000, 7300, '기념품제작', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 7300);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 7000, 7400, '모형제작', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 7400);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 7000, 7500, '시스템제작', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 7500);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 7000, 7600, '인테리어시공', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 7600);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME, IMG_URL)
SELECT 7000, 7700, '패키지제작', NULL
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 7700);
